### ISSUE TITLE
Timer calls outside of the gen server

### ISSUE THREAD

**Issue by nwolverson** [id3as/purescript-erl-pinto#1]
```purescript
sendAfter :: forall state. ServerName state -> Int -> (state -> Effect state) -> Effect TimerRef
```
This takes the server name, which is then discarded in the FFI, the timer message is just sent to the calling process.

I accidentally called this from spawned process which of course gets an unexpected message (I'd say also violating the typed process concept in `erl-process`).

Would be great if we can tweak types or implementation to make this less error-prone.

**Comment by robashton** [comment]
I'm thinking that most things should be done the erl-process way at this point; it doesn't make sense to have a lot of special-case code for gen servers/etc. At this point in [client-name] codebase I've got 4-5 different ways of handling arbitrary messages and erl-process and plain ol' callbacks clearly win the day.

**Comment by robashton** [comment]
Ok, done - now looks more like

```purescript
tickRef <- Timer.sendAfter afterMs (handleTick channel.id)

handleTick :: ChannelId -> Effect Unit
handleTick id = 
  Gen.doCall (serverName id) \state -> 
     pure $ CallReply unit state
```
Vanilla callbacks, and up to the user to capture enough information in order to get the message back to the parent process.
