### ISSUE TITLE
`Global Atom` as `ServerName` is too specific.

### ISSUE THREAD

**Issue by GoNZooo** [id3as/purescript-erl-pinto#11]
`global` allows for any term to be registered as an identifier for a process, which means that `Atom` is too restrictive and encourages filling the atom table for things like transient processes, potentially with UUIDs or the like.

While writing some pg2 and global wrappers I made a type class `ToName` that provides a reasonable experience around this, though in reality it's really all about making something a `term()` which I assume means `Foreign`.

The actual type of `registerName` is:

```purescript
registerName :: ∀ name. ToName name => name -> Pid -> Effect (Maybe Unit)
```

**Comment by adrianroe** [comment]
You are quite right.  We basically never use global (we tend to use via and gproc, even for local stuff and we tend not to use erlang messaging across servers).

**Comment by adrianroe** [comment]
How about [Change Global name payload to be foreign GlobalName](https://github.com/id3as/purescript-erl-pinto/commit/014bb9ad73273a4f0198629133c3c6d394ab9208)

**Comment by GoNZooo** [comment]
I think it would be more accurate or at least more cohesive to say `Global Foreign`. The second argument to `Via module name` is `Foreign` and is where the name passed to `Global` would go.

`{via, global, Name :: term()}` is valid as a `via` tuple AFAIK and the `{global, name}` is effectively a shortcut for the same.

More than that, `global` has a freestanding interface outside of name tuples and you do want to create these names on the fly when registering groups and such. For any arbitrary `term()` process registry you're going to want to have the type be constructible from data.

Personally, I think a change like the following would make sense:

```purescript
data ServerName state msg name =
  Local Atom
  | Global name
  | Via NativeModuleName name

class ToName name where
  toName :: name -> Foreign

whereIsName :: ∀ name. ToName name => name -> Effect (Maybe Pid)
whereIsName = whereIsName_ Nothing Just <<< ProcessRegistry.toName

-- User code
newtype UserId = UserId String
derive instance userIdNewtype :: Newtype UserId _
instance userIdToName :: ToName UserId where
  toName (UserId id) =
    ProcessRegistry.toName $ ErlTuple.tuple2 (Atom.atom "User") id
```

As you can see I'm already using this pattern and registering global names outside of `startLink` instead because of the limitations of the current API (I've added a `startLinkWithoutName` function to not have to specify anything, as that is also too limiting). It's also useful for `pg2`, etc., hence the general `ProcessRegistry` module.

**Comment by adrianroe** [comment]
Not sure I like the suggested ServerName change - there's no reason Global name and Via ... name should use the same name type - they really are just foreign types.

I quite like the idea of adding foreign type names for those names, but that is only to make type declarations read nicely (which is pretty much all any foreign import can do and you can only create them with a coerce or with FFI).

Does your whereIsName suggestion work - I'm not aware of something what would transparently allow a lookup based on via or on global, but I may well be wrong, as I never use global!

Thanks for your input - enjoying the discussion!

**Comment by GoNZooo** [comment]
`global` and `via` do actually have a connection:
 
`GlobalName = ViaName = term()` as per the [OTP docs](http://erlang.org/doc/man/gen_server.html#call-3). The rules that apply to `global` are the rules that apply to all valid `via` registries, because `global` is really just an implementation of those AFAIU.

About the underlying type:

That's fair. As long as there is an obvious way to create these from any reifiable value the user has I guess I'm not so concerned about the underlying type spec. I think a type class goes a long way here to signal that there is a pre-requisite and contract in place to ensure that things work out.

With the following pre-requisites:

```purescript
whereIsName :: ∀ name. ToName name => name -> Effect (Maybe Pid)
whereIsName = whereIsName_ Nothing Just <<< ProcessRegistry.toName

registerName :: ∀ name. ToName name => name -> Pid -> Effect (Maybe Unit)
registerName = registerName_ Nothing Just <<< ProcessRegistry.toName

foreign import whereIsName_ ::
    Maybe Pid
 -> (Pid -> Maybe Pid)
 -> Foreign
 -> Effect (Maybe Pid)

foreign import registerName_ ::
    Maybe Unit
 -> (Unit -> Maybe Unit)
 -> Foreign
 -> Pid
 -> Effect (Maybe Unit)
```

This works and will output "Same pid in global".

```purescript
init :: Args -> Effect State
init id = do
  ownPid <- Utilities.selfPid

  globalRegisterResult <- Global.registerName id ownPid  
  pg2RegisterResult <- Pg2.createAndJoin (Atom.atom "Users") ownPid
  case globalRegisterResult of
    Just _ ->
      case pg2RegisterResult of
        Just _ -> do
          maybePid1 <- Global.whereIsName id
          case maybePid1 of
            Just pid | ownPid == pid ->
              Console.log "Same pid in global"

            Just _ ->
              Console.log "Different pid in global"
            
            Nothing ->
              Console.log "Pid not registered"
          pure $ State {id, channels: ErlList.nil}

        Nothing ->
          Exception.throw "Unable to register user process in `pg2`"

    Nothing ->
      Exception.throw "Unable to register user process in `global`"
```

The `Pg2` module is based on the same principle; anything you can turn into a name goes.

**Comment by GoNZooo** [comment]
Having given this some thought I think it might be a valid idea to remove `Global` as a constructor for `ServerName`. If one wants to register via `global` one can simply do so via `Via (NativeModuleName $ atom "global") (term :: Foreign/ProcessName/ErlTerm)`.

Maybe this would create perceived friction when coming from Erlang, but given the redundant nature of `{global, ...}` as a registration tuple it makes sense to not only look at making the constructor accurate but also examine whether or not it's warranted from the beginning.

**Comment by robashton** [comment]
Just an update on the movement of this @GoNZooo - I've been bogged down with non-purerl work the last few weeks so I'm behind on pull requests/branches/etc. We are going to unify our various experiements back to master and then revisit this issue and see how it fits in.

**Comment by robashton** [comment]
And  another update, I've merged in the unifytypes branch which contained the work around this - hopefully this should suffice  - few more changes on their way too..
